
sudo: required
services:
   - docker

before_install:
   - docker build -t syed/docker-react -f Dockerfile.dev .

script:
   - docker run syed/docker-react npm run test -- --coverage 

deploy:
   provider: elasticbeanstalk
   region:  "us-east-1"
   app: "frontend"
   env: "Frontend-env"
   bucket_name: "elasticbeanstalk-us-east-1-590558394204"
   bucket_path: "frontend"
   on:
      branch: master
   access_key_id: "$AWS_ACCESS_KEY"
   secret_access_key: "$AWS_SECRET_KEY"

   


    

    
